### ISSUE TITLE
Feature: 支持修改和删除 device.json

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi-plugin-gocqhttp#12]
大致有两种方案：

## 方案 1

添加单一配置项 gocqhttp.device，用户可以在这里配置使用的设备类型。

每次启动时，如果没有 device.json，则根据此项配置创建；如果此配置与现有的 device.json 不一致，则重新创建。

- Q：为什么不在控制台允许配置 device.json 中的每一个属性？
- A：因为 device.json 中的部分属性是随机生成的，不方便设置默认值。

## 方案 2

为每个 onebot 实例增加上传和下载 device.json 和 session.token 文件的按钮。

并增加一个额外的「创建新设备」按钮，可以弹出对话框配置 protocol 等属性。

**Comment by wc7086** [comment]
等`cq-http`自动生成`device.json`后再读取`protocol`字段就足够了吧。其他的都不用管，因为 json 可读性已经够好了，要改的属性多直接格式化一下 json 就行
