### ISSUE TITLE
bug: voice convert failed after bumping the version

### ISSUE THREAD

**Issue by darwintree** [koishijs/koishi-plugin-gocqhttp#13]
版本更新后语音转换出现问题

![image](https://user-images.githubusercontent.com/17946284/213058670-d452de4e-b741-4b34-8781-5c91ae31412b.png)

`Error: Error with request send_group_msg, args: {"group_id":"427698449","message":[{"type":"record","data":{"file":"https://strawberrytree.top/convert/cache/sounds/voice/events/produce_events/200201511/2002015110120.m4a"}}]}, retcode: 100`

其问题描述与 https://github.com/Mrs4s/go-cqhttp/issues/1831 一致。推测为上游go-cqhttp的问题

**Comment by darwintree** [comment]
目前使用的临时解决方案: 修改 package.json
`    "koishi-plugin-gocqhttp": "^3.2.1",`
为
`    "koishi-plugin-gocqhttp": "3.2.1",`
回退依赖版本

**Comment by shigma** [comment]
上游现已修复但是仍未发版。我们会等待上游解决。

**Comment by shigma** [comment]
新版本已解决此问题。
