### ISSUE TITLE
Feature: 支持配置是否显示 debug 等级日志（所有收发消息）

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi-plugin-gocqhttp#15]
来自用户群内 2 位小伙伴的功能请求：

上个版本的 gocq 插件存在来自 go-cqhttp 的 bug，debug 等级的日志会默认显示，导致了较大的日志体积。gocq 侧已将此 bug 修复，最新版本插件已经不会再显示 debug 等级的日志。

但与此同时，Koishi 控制台将无法看到 gocq 收发的消息，对以前通过 Koishi 控制台日志除错的小伙伴造成了不便。

希望能够添加日志等级选项，提供一种恢复所有收发消息记录日志的方案。

**Comment by shigma** [comment]
我们提供了 logLevel 配置项，目前默认为 2（低于 3.3.0 版本时为 3）。

此配置项可以通过控制台更改，应该能解决此 issue 中提出的需求？

**Comment by ilharp** [comment]
应该可以解决。在用户亲测解决后我会关闭此 issue。

**Comment by ilharp** [comment]
用户群用户已亲测可用

**Comment by auqhjjqdo** [comment]
请问这个loglevel的数字分别对应哪些log等级，能否在文档添加相关注释

**Comment by ilharp** [comment]
> 请问这个loglevel的数字分别对应哪些log等级，能否在文档添加相关注释

不错的建议，但独立的 feature request 请新建一个 issue，不要在已解决的 issue 里讨论其他话题。
