### ISSUE TITLE
能否暴露gocqhttp的端口供外部机器人使用？

### ISSUE THREAD

**Issue by vzcrab** [koishijs/koishi-plugin-gocqhttp#22]
感谢开发此插件。

我想配置 [`chatgpt-mirai-qq-bot` ](https://github.com/lss233/chatgpt-mirai-qq-bot) ，其 onebot 配置项只提供host和port字段。
```
[onebot]
qq=请修改为你机器人的QQ号
manager_qq = 请修改为机器人管理员的QQ号

reverse_ws_host = "0.0.0.0"
reverse_ws_port = 8566
```

该插件的 gocqhttp 貌似是监听在 `ws://<host:port>/onebot` ？

在配置页可以配置 host 监听所有地址，却没有端口配置，不知理解是否正确。

**Comment by shigma** [comment]
端口就是 Koishi 自己的端口，在「全局设置」里可以看到。

**Comment by vzcrab** [comment]
> 端口就是 Koishi 自己的端口，在「全局设置」里可以看到。

谢谢回复，@shigma 

不好意思，我没有说清楚。

koishi 自身只暴露一个端口， chatgpt-mirai-qq-bot 直接配置无法连接，从koishi onebot 端的配置看，加了 `/onebot` 路径。

而  chatgpt-mirai-qq-bot 目前只支持 host+prot 的配置方式，不支持带路径的 ws 连接。

检索了一下资料发现，发现在 onebot 标准中定义的连接配置项，反向ws、http post是配置url，而正向、http方式是host+port，可能是大伙为了实现方便，就全用了 host+port。并且两边都把host+port后面路径部分硬编码了，造成现在这种局面。

现在有另一种思路了，可以让 ws 反向连接中路径部分成为配置项。

以上。

---
不知你认为是否需要修改。如果不用修改，这个议题就可以关了。因为我需求变了暂时用不上了。

**Comment by shigma** [comment]
> 加了 `/onebot` 路径

这个可以改，在 onebot 插件的 `path` 配置项（但是改掉以后路由会跟 console 插件冲突，你还需要改 console 的 `uiPath` 配置项）。

论其根本我认为这是其他生态没有做好支持所致。一个提供网络服务的软件居然不支持配置路径已经很奇怪了。

**Comment by vzcrab** [comment]
啊这，原来这两边可以同步啊。全局设置里可以改端口、onebot里可以改路径。那没事了😂
