### ISSUE TITLE
安装此插件后出现报错

### ISSUE THREAD

**Issue by jiajiu123** [koishijs/koishi-plugin-gocqhttp#3]
[2022-02-13.log](https://github.com/koishijs/koishi-plugin-gocqhttp/files/8055487/2022-02-13.log)
系统为Ubuntu 20.04LTS，Yarn版本为1.22.17，NodeJS版本为16.14.0，Koishi版本为4.1.2，koishi-plugin-gocqhttp版本为2.1.0

**Comment by MaikoTan** [comment]
Can you still reproduce this error now with the latest release?

**Comment by MaikoTan** [comment]
This issue is staled for a long time and cannot be reproduced, so close it.
If someone has the same issue even with the latest release, then they can reopen the issue or produce a new one.
